services:
  - type: web
    name: recipes-on-render
    env: node
    plan: free
    buildCommand: npm install && npm run prisma:generate && npm run prisma:deploy
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: DATABASE_URL
        fromDatabase: 
          name: recipes-db
          property: connectionString
    healthCheckPath: /healthz

databases:
  - name: recipes-db
    plan: free


